env:
  browser: true
  es2021: true
extends:
  - standard
rules:
 semi: 
  - true
  - 2
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {}
overrides:
  -env:
    jest: true
